### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by PaladinDD** [Serene-Arc/bulk-downloader-for-reddit#543]
After installing and running one of the examples. I get
```bash
$ python3 -m bdfr download ./path/to/output --subreddit Python -L 10
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/priv/strokecontrol/venv/lib/python3.8/site-packages/bdfr/__main__.py", line 8, in <module>
    from bdfr.archiver import Archiver
  File "/mnt/priv/strokecontrol/venv/lib/python3.8/site-packages/bdfr/archiver.py", line 15, in <module>
    from bdfr.archive_entry.submission_archive_entry import SubmissionArchiveEntry
  File "/mnt/priv/strokecontrol/venv/lib/python3.8/site-packages/bdfr/archive_entry/submission_archive_entry.py", line 13, in <module>
    class SubmissionArchiveEntry(BaseArchiveEntry):
  File "/mnt/priv/strokecontrol/venv/lib/python3.8/site-packages/bdfr/archive_entry/submission_archive_entry.py", line 41, in SubmissionArchiveEntry
    def _get_comments(self) -> list[dict]:
TypeError: 'type' object is not subscriptable
```
Downloading a subreddit always results in that error. I run the software on Ubuntu Linux

**Comment by Borlean** [comment]
Just for others that come across this issue, I was able to get it working by modifying the installation code: 

`python3 -m pip install bdfr --upgrade`
to 
`python3.9 -m pip install bdfr --upgrade`
