### ISSUE TITLE
[BUG] Comment not in the comment tree

### ISSUE THREAD

**Issue by 8ullyMaguire** [Serene-Arc/bulk-downloader-for-reddit#799]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

When running the Bulk downloader for reddit program, the following error occurs:

```python
Traceback (most recent call last):
  File "/home/user/.local/bin/bdfr", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/bdfr/__main__.py", line 161, in cli_clone
    reddit_scraper.download()
  File "/home/user/.local/lib/python3.10/site-packages/bdfr/cloner.py", line 27, in download
    self.write_entry(submission)
  File "/home/user/.local/lib/python3.10/site-packages/bdfr/archiver.py", line 92, in write_entry
    self._write_entry_json(archive_entry)
  File "/home/user/.local/lib/python3.10/site-packages/bdfr/archiver.py", line 103, in _write_entry_json
    content = json.dumps(entry.compile())
  File "/home/user/.local/lib/python3.10/site-packages/bdfr/archive_entry/comment_archive_entry.py", line 18, in compile
    self.source.refresh()
  File "/usr/lib/python3.10/site-packages/praw/models/reddit/comment.py", line 298, in refresh
    raise ClientException(self.MISSING_COMMENT_MESSAGE)
praw.exceptions.ClientException: This comment does not appear to be in the comment tree
```

## Command

```text
bdfr clone . --user reddituser --submitted --all-comments --file-scheme '{DATE}_{POSTID}' --folder-scheme ''
```

## Environment (please complete the following information)

- OS: Manjaro Linux
- Python version: Python 3.10.9

## Logs

I haven't found the log file.

**Comment by Serene-Arc** [comment]
Log files are **required**. The section of the documents that you ticked as having read states the location of the log files. Please supply them or this issue will be summarily closed for lack of information.
