### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hesamjokar** [Serene-Arc/bulk-downloader-for-reddit#854]
I am reporting a bug that I have been facing with recently. First things first:
1. I am running the latest version of BDfR
2. I am running Python 3.9.13 (Anaconda package)
3. BDfR was working perfectly until 6 months ago on this exact same configuration
4. Running the applet from command prompt and anaconda prompts results the same.

A. When running BDfR, first, the prompt warns about mkl-service, which is installed and up-to-date:
`C:\Users\me\anaconda3\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service`
Sometimes it stops there, otherwise it proceeds to the next part (B).

B. If not stopping at part A, the attached log prompts (see Logs at the end).

Utilizing various virtual machine configurations (Python packages 3.9, 3.10, 3.11; Windows 10 and 11) also had no effect and the results were the same.

## Command

```text
python -m bdfr download ./path/to/output --user me --saved --authenticate --file-scheme '{REDDITOR}_{SUBREDDIT}_{TITLE}_{POSTID}' --folder-scheme '' --no-dupes
```

## Environment (please complete the following information)

- OS: Windows 11 Pro, 22H2
- Python version: 3.9.13
- Conda version: 23.3.1

## Logs

```text
[date time - bdfr.downloader - ERROR] - Site Redgifs failed to download submission 136rz90: Failed to get page https://api.redgifs.com/v2/gifs/quarterlysuburbanfinnishspitz
Traceback (most recent call last):
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\me\anaconda3\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\me\anaconda3\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Users\me\anaconda3\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\anaconda3\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\me\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\me\anaconda3\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\me\anaconda3\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Users\me\anaconda3\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\anaconda3\lib\site-packages\bdfr\__main__.py", line 222, in <module>
    cli()
  File "C:\Users\me\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\me\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\me\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\me\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\bdfr\__main__.py", line 118, in cli_download
    reddit_downloader.download()
  File "C:\Users\me\anaconda3\lib\site-packages\bdfr\downloader.py", line 50, in download
    self._download_submission(submission)
  File "C:\Users\me\anaconda3\lib\site-packages\bdfr\downloader.py", line 107, in _download_submission
    content = downloader.find_resources(self.authenticator)
  File "C:\Users\me\anaconda3\lib\site-packages\bdfr\site_downloaders\redgifs.py", line 22, in find_resources
    media_urls = self._get_link(self.post.url)
  File "C:\Users\me\anaconda3\lib\site-packages\bdfr\site_downloaders\redgifs.py", line 65, in _get_link
    if requests.get(response_json["gif"]["urls"]["hd"], headers=headers).ok:
  File "C:\Users\me\anaconda3\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\me\anaconda3\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by OMEGARAZER** [comment]
what steps did you use to install with conda? Numpy is not something that's installed by BDFR or any of the dependencies and seems to be what's causing the first issue. Any more than that I have no idea as being unfamiliar with conda I don't know why it would even attempt to import something that's not used or needed by BDFR.
