### ISSUE TITLE
[BUG] Connection dies mid run 

### ISSUE THREAD

**Issue by ghost** [Serene-Arc/bulk-downloader-for-reddit#905]

**Comment by Serene-Arc** [comment]
Please post the full logs. This is **not optional**. Posting the stack trace is not enough.

**Comment by MrPromotor** [comment]
i have the same problem, i think is only with redgifs posts

**Comment by ynynynynty11** [comment]
Yes sorry i hope this one can help 

[2023-07-03 01:51:27,693 - bdfr.site_downloaders.youtube - ERROR] - [0;31mERROR:[0m [PornHub] 9892792927098927043170431: Unable to download webpage: <urlopen error timed out> (caused by URLError(TimeoutError('timed out')))
Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1451, in connect
    super().connect()
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 835, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3786, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 1514, in https_open
    return self.do_open(
           ^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\pornhub.py", line 283, in _real_extract
    webpage = dl_webpage('pc')
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\pornhub.py", line 279, in dl_webpage
    return self._download_webpage(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1111, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1062, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\pornhub.py", line 37, in _download_webpage_handle
    ret = dl(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\pornhub.py", line 35, in dl
    return super(PornHubBaseIE, self)._download_webpage_handle(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 896, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 853, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [PornHub] 9892792927098927043170431: Unable to download webpage: <urlopen error timed out> (caused by URLError(TimeoutError('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\site_downloaders\youtube.py", line 73, in get_video_data
    result = ydl.extract_info(url, download=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1544, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1573, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1036, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 976, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: [0;31mERROR:[0m [PornHub] 9892792927098927043170431: Unable to download webpage: <urlopen error timed out> (caused by URLError(TimeoutError('timed out')))
[2023-07-03 01:51:27,696 - bdfr.downloader - ERROR] - Site PornHub failed to download submission 2yoqxd: Video info extraction failed for http://www.pornhub.com/view_video.php?viewkey=9892792927098927043170431

**Comment by ynynynynty11** [comment]
and this one is from another logs file in the same folder with diff number 

[2023-07-02 23:47:58,221 - bdfr.downloader - DEBUG] - Using Redgifs with url https://www.redgifs.com/watch/test
[2023-07-02 23:48:02,995 - root - ERROR] - Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 710, in _error_catcher
    yield
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 835, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(2823982 bytes read, 35983678 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 940, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 911, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 813, in _raw_read
    with self._error_catcher():
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(2823982 bytes read, 35983678 more expected)', IncompleteRead(2823982 bytes read, 35983678 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\__main__.py", line 118, in cli_download
    reddit_downloader.download()
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\downloader.py", line 50, in download
    self._download_submission(submission)
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\downloader.py", line 107, in _download_submission
    content = downloader.find_resources(self.authenticator)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\site_downloaders\redgifs.py", line 22, in find_resources
    media_urls = self._get_link(self.post.url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\bdfr\site_downloaders\redgifs.py", line 65, in _get_link
    if requests.get(response_json["gif"]["urls"]["hd"], headers=headers).ok:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 747, in send
    r.content
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Left\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(2823982 bytes read, 35983678 more expected)', IncompleteRead(2823982 bytes read, 35983678 more expected))

**Comment by Serene-Arc** [comment]
Again, you need to post **UNALTERED AND COMPLETE LOGS**. This is clearly said in the document for opening an issue that you said you read. Do not change the log files, do not cut them off, just post them as they are.
