### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ClaireCJS** [Serene-Arc/bulk-downloader-for-reddit#916]
- [x] I am reporting a bug.
- [x] I am running the latest version of BDfR
- [x] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

Can't run more than one instance at a time

## Command

```text
(any)
```

## Environment (please complete the following information)

- OS: Windows 10
- Python version: 3.10.9

## Logs

```text
Cannot rollover logfile, make sure this is the only BDFR process or specify alternate logfile location
Downloader exited unexpectedly
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\__main__.py", line 117, in cli_download
    reddit_downloader = RedditDownloader(config, [stream])
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\downloader.py", line 41, in __init__
    super(RedditDownloader, self).__init__(args, logging_handlers)
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\connector.py", line 60, in __init__
    file_log = self.create_file_logger()
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\connector.py", line 227, in create_file_logger
    file_handler.doRollover()
  File "C:\ProgramData\anaconda3\lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\ProgramData\anaconda3\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ClioC\\AppData\\Local\\BDFR\\bdfr\\log_output.txt' -> 'C:\\Users\\ClioC\\AppData\\Local\\BDFR\\bdfr\\log_output.txt.1'
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\Scripts\bdfr.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\__main__.py", line 117, in cli_download
    reddit_downloader = RedditDownloader(config, [stream])
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\downloader.py", line 41, in __init__
    super(RedditDownloader, self).__init__(args, logging_handlers)
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\connector.py", line 60, in __init__
    file_log = self.create_file_logger()
  File "C:\ProgramData\anaconda3\lib\site-packages\bdfr\connector.py", line 227, in create_file_logger
    file_handler.doRollover()
  File "C:\ProgramData\anaconda3\lib\logging\handlers.py", line 179, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "C:\ProgramData\anaconda3\lib\logging\handlers.py", line 115, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ClioC\\AppData\\Local\\BDFR\\bdfr\\log_output.txt' -> 'C:\\Users\\ClioC\\AppData\\Local\\BDFR\\bdfr\\log_output.txt.1'
```

**Comment by Serene-Arc** [comment]
This is explained in the README. Due to how Windows works with files, if you use multiple instances you have to manually specify the log files to use. Else it will find the file already in use and windows will fail.
