### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'emoji'

### ISSUE THREAD

**Issue by madhatr** [Serene-Arc/bulk-downloader-for-reddit#942]
This is from FORK [bulk-downloader-for-reddit_with-saved-hashes](https://github.com/thomas694/bulk-downloader-for-reddit_with-saved-hashes)

I over wrote the bdfr folder with the bdfr folder inside the zip and this is the error I get. Before doing this bdfr works fine. 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\bdfr.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\bdfr\__main__.py", line 11, in <module>
    from bdfr.archiver import Archiver
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\bdfr\archiver.py", line 25, in <module>
    from bdfr.connector import RedditConnector
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\bdfr\connector.py", line 32, in <module>
    from bdfr.file_name_formatter import FileNameFormatter
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\bdfr\file_name_formatter.py", line 12, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'
```

**Comment by Serene-Arc** [comment]
You need to install the module `emoji` from pip. Do this however your normally install python packages from pypi.
