### ISSUE TITLE
[BUG] Archive command returns PRAW exception 'No data returned for comment' when using --link on posts made after 2023-01-01

### ISSUE THREAD

**Issue by jtjb07** [Serene-Arc/bulk-downloader-for-reddit#964]
## Description

I'm attempting to archive `1e1qekj`. Using `--link` causes the program to crash, but the post successfully archives when using `--subreddit`. At first I thought it was due to deleted comments, but it's occurring for any post specified with --link

## Command
Unsuccessful command:
```
bdfr archive "" --link 1e1qekj
```
Successful command:
```
bdfr archive "" --subreddit koibu
```

## Environment
- OS: Windows 10.0.19045 Home
- Python version: 3.11.4

## Log
```
[2024-07-16 11:35:17,196 - bdfr.connector - DEBUG] - Disabling the following modules: 
[2024-07-16 11:35:17,196 - bdfr.connector - Level 9] - Created download filter
[2024-07-16 11:35:17,196 - bdfr.connector - Level 9] - Created time filter
[2024-07-16 11:35:17,206 - bdfr.connector - Level 9] - Created sort filter
[2024-07-16 11:35:17,222 - bdfr.connector - Level 9] - Create file name formatter
[2024-07-16 11:35:17,222 - bdfr.connector - DEBUG] - Using unauthenticated Reddit instance
[2024-07-16 11:35:17,222 - bdfr.connector - Level 9] - Created site authenticator
[2024-07-16 11:35:17,222 - bdfr.connector - Level 9] - Retrieved subreddits
[2024-07-16 11:35:17,222 - bdfr.connector - Level 9] - Retrieved multireddits
[2024-07-16 11:35:17,222 - bdfr.connector - Level 9] - Retrieved user data
[2024-07-16 11:35:17,228 - bdfr.connector - Level 9] - Retrieved submissions for given links
[2024-07-16 11:35:17,805 - root - ERROR] - Archiver exited unexpectedly
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\bdfr\__main__.py", line 139, in cli_archive
    reddit_archiver.download()
  File "C:\Python311\Lib\site-packages\bdfr\archiver.py", line 37, in download
    if (submission.author and submission.author.name in self.args.ignore_user) or (
        ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\praw\models\reddit\base.py", line 35, in __getattr__
    self._fetch()
  File "C:\Python311\Lib\site-packages\praw\models\reddit\comment.py", line 192, in _fetch
    raise ClientException(f"No data returned for comment {self.fullname}")
praw.exceptions.ClientException: No data returned for comment t1_1e1qekj
```
## Update
Edit: After more testing, it appears this is only happening on newer posts, after approximately 2023-01-01. Any posts made after this date have the aforementioned issue, while those made before archive successfully.

`100xkkz` GMT +11 2023-01-02 11:00:20, fails to archive using `bdfr archive "" --link 100xkkz`
`zwtso2` GMT +11 2022-12-28 10:30:20, successfully archives using `bdfr archive "" --link zwtso2`

**Comment by jtjb07** [comment]
Never mind, already solved by #783
