### ISSUE TITLE
Struggling to install. 

### ISSUE THREAD

**Issue by Binocularbath** [Serene-Arc/bulk-downloader-for-reddit#976]
- [ x] I am reporting a bug.
- [x ] I am running the latest version of BDfR
- [x ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description

I have spent most of the night trying to install BDFR. I have read documentation and am using google to try to fix things as they come up but i am struggling. Id love to use this program. Is someone able to help me with this. I know this mean the config file is corrupt but what can i do to fix it. I try forced reinstall but it doesnt change the outcome.

Any help welcome, thank you

## Command
BDFR --user {REDDITUSER} --submitted -L 10

## Environment (please complete the following information)

- OS: Windows 11
- Python version: 3.13

## Logs

```text
Paste the log output here.
```

> 
> C:\Users\Binocularbath>bdfr download C:\BDFR --user binocularbath--submitted -L 10
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\Binocularbath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts\bdfr.exe\__main__.py", line 4, in <module>
>     from bdfr.__main__ import cli
>   File "C:\Users\Binocularbath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bdfr\__main__.py", line 11, in <module>
>     from bdfr.archiver import Archiver
>   File "C:\Users\Binocularbath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bdfr\archiver.py", line 21, in <module>
>     from bdfr.connector import RedditConnector
>   File "C:\Users\Binocularbath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bdfr\connector.py", line 29, in <module>
>     from bdfr.oauth2 import OAuth2Authenticator, OAuth2TokenManager
>   File "C:\Users\Binocularbath\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bdfr\oauth2.py", line 90, in <module>
>     class OAuth2TokenManager(praw.reddit.BaseTokenManager):
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'praw.reddit' has no attribute 'BaseTokenManager'

Python 3.13

**Comment by Binocularbath** [comment]
User NulledExceptions suggested a fix [here](https://github.com/Serene-Arc/bulk-downloader-for-reddit/issues/970#issuecomment-2456201893)

> Temporary workaround
> pip3 install praw==7.7.1

Worked perfectly

**Comment by EkriirkE** [comment]
#1012 will resolve this soon
